[project]
name = "mocdatacreator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cython>=3.2.0",
    "faker>=37.12.0",
    "setuptools>=80.9.0",
]
